import { readDb } from "@/lib/store";

/** Every automated message is logged here; in production an email provider sends them. */
export default function Outbox() {
  const msgs = [...readDb().outbox].reverse();
  return (
    <>
      <h1>Outbox</h1>
      <p className="sub">Messages generated by the workflow ({msgs.length}). The prototype logs them instead of sending real email.</p>
      <div className="card">
        <div className="table-wrap">
          <table>
            <thead><tr><th>Time (UTC)</th><th>Type</th><th>To</th><th>Subject</th><th>Body</th></tr></thead>
            <tbody>{msgs.map((m) => (
              <tr key={m.id}><td>{m.createdAt.slice(0, 16).replace("T", " ")}</td><td><span className="pill info">{m.kind.replace("_", " ")}</span></td><td>{m.to}</td><td>{m.subject}</td><td className="muted">{m.body}</td></tr>
            ))}</tbody>
          </table>
        </div>
      </div>
    </>
  );
}
